# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(unique=True)),
                ('total_daily_passengers', models.PositiveIntegerField(default=0)),
                ('total_active_routes', models.PositiveIntegerField(default=0)),
                ('total_active_buses', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('fleet_availability_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='TenantAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(max_length=63)),
                ('snapshot_date', models.DateField()),
                ('total_vehicles', models.PositiveIntegerField(default=0)),
                ('active_vehicles', models.PositiveIntegerField(default=0)),
                ('total_drivers', models.PositiveIntegerField(default=0)),
                ('trips_today', models.PositiveIntegerField(default=0)),
                ('daily_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fleet_utilization', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('open_complaints', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['tenant_schema', 'snapshot_date'], name='analytics_t_tenant__cbaa2b_idx')],
                'unique_together': {('tenant_schema', 'snapshot_date')},
            },
        ),
    ]
