# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('alert_type', models.CharField(choices=[('LOW_MILEAGE', 'Low Mileage'), ('SUSPECTED_THEFT', 'Suspected Theft')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MileageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('km_run', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_consumed', models.DecimalField(decimal_places=2, max_digits=8)),
                ('mileage_kmpl', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle_id', 'period_start'], name='fuel_mileag_vehicle_351642_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('driver_id', models.UUIDField()),
                ('date', models.DateField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('odometer_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_by_id', models.UUIDField(blank=True, null=True)),
                ('station', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['vehicle_id', 'date'], name='fuel_fuelis_vehicle_7e2f52_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate_per_liter', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_issuance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='fuel.fuelissuance')),
            ],
        ),
    ]
