# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_uid', models.CharField(max_length=30, unique=True)),
                ('ticket_type_id', models.UUIDField()),
                ('trip_id', models.UUIDField()),
                ('passenger_id', models.UUIDField(blank=True, null=True)),
                ('conductor_id', models.UUIDField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('fare_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('SMART_CARD', 'Smart Card'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti')], max_length=15)),
                ('qr_code', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='VALID', max_length=10)),
                ('from_stop_id', models.UUIDField(blank=True, null=True)),
                ('to_stop_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['ticket_uid'], name='ticketing_t_ticket__73417b_idx'), models.Index(fields=['trip_id'], name='ticketing_t_trip_id_4a8edb_idx'), models.Index(fields=['status'], name='ticketing_t_status_df2281_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_id', models.UUIDField()),
                ('school', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_pass_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['passenger_id'], name='ticketing_s_passeng_660f65_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_id', models.UUIDField()),
                ('month', models.DateField(help_text='First day of the month')),
                ('fare_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('route_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['passenger_id', 'month'], name='ticketing_m_passeng_65a0cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_id', models.UUIDField()),
                ('date', models.DateField()),
                ('fare_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('usage_count', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('passenger_id', 'date')},
            },
        ),
    ]
