# Generated by Django 4.2.16 on 2026-09-16 14:44

from django.db import migrations, models
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_pos_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamastePayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('environment', models.CharField(choices=[('TEST', 'Test'), ('LIVE', 'Live')], default='TEST', max_length=4)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('SMART_CARD', 'Smart Card'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('FONEPAY', 'Fonepay'), ('CONNECTIPS', 'ConnectIPS'), ('NAMASTEPAY', 'NamastePay')], default='CASH', max_length=15),
        ),
    ]
