# Generated by Django 4.2.16 on 2026-09-17 06:03

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_namastepayconfig_alter_ticket_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namastepayconfig',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='namastepayconfig',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='namastepayconfig',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
