# Generated by Django 4.2.16 on 2026-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_remove_namastepayconfig_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='vehicle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
