# Generated by Django 4.2.16 on 2026-09-20 04:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_ticket_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_id', models.UUIDField(blank=True, null=True)),
                ('route_id', models.UUIDField(blank=True, null=True)),
                ('from_stop_id', models.UUIDField(blank=True, null=True)),
                ('to_stop_id', models.UUIDField(blank=True, null=True)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('SMART_CARD', 'Smart Card'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('FONEPAY', 'Fonepay'), ('CONNECTIPS', 'ConnectIPS'), ('NAMASTEPAY', 'NamastePay')], default='CASH', max_length=15)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('CANCELLED', 'Cancelled')], default='VALID', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-booked_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticketing.booking'),
        ),
    ]
