# Generated by Django 4.2.16 on 2026-09-20 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0006_booking_ticket_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamastePayCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_id', models.CharField(max_length=100, unique=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('passenger_id', models.UUIDField(blank=True, null=True)),
                ('route_id', models.UUIDField(blank=True, null=True)),
                ('from_stop_id', models.UUIDField(blank=True, null=True)),
                ('to_stop_id', models.UUIDField(blank=True, null=True)),
                ('passengers', models.JSONField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('return_to', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketing.booking')),
            ],
        ),
    ]
