# Generated by Django 4.2.16 on 2026-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_namastepaycheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='namastepaycheckout',
            name='vehicle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namastepaycheckout',
            name='return_to',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
