# Generated by Django 4.2.16 on 2026-09-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_namastepaycheckout_vehicle_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='to_stop_id',
        ),
        migrations.RemoveField(
            model_name='namastepaycheckout',
            name='to_stop_id',
        ),
    ]
