# Generated by Django 4.2.16 on 2026-09-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0009_remove_booking_to_stop_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
