# Generated by Django 4.2.16 on 2026-09-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0010_ticket_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namastepaycheckout',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='namastepaycheckout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=9),
        ),
    ]
