# Generated by Django 4.2.16 on 2026-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0011_alter_namastepaycheckout_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namastepaycheckout',
            name='conductor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
