# Generated by Django 4.2.16 on 2026-06-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='accounting__account_cc17c6_idx',
            old_name='accounting_coa_type_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='accounting__code_569b11_idx',
            old_name='accounting_coa_code_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__date_e3f521_idx',
            old_name='accounting_je_date_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__status_0a2ff9_idx',
            old_name='accounting_je_status_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__source__1f5d97_idx',
            old_name='accounting_je_source_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounting__entry_n_69cf73_idx',
            old_name='accounting_je_no_idx',
        ),
        migrations.RenameIndex(
            model_name='salarypayment',
            new_name='accounting__employe_95478b_idx',
            old_name='accounting_sp_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='salarypayment',
            new_name='accounting__status_e5f58f_idx',
            old_name='accounting_sp_status_idx',
        ),
    ]
