# Generated by Django 4.2.16 on 2026-06-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_chartofaccount_new_coa_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='accounting__parent__c2206e_idx',
            old_name='accounting__parent_code_idx',
        ),
    ]
