# Generated by Django 4.2.16 on 2026-06-22 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('route_id', models.UUIDField()),
                ('vehicle_id', models.UUIDField()),
                ('driver_id', models.UUIDField(blank=True, null=True)),
                ('conductor_id', models.UUIDField(blank=True, null=True)),
                ('shift_start', models.TimeField(default='05:00')),
                ('shift_end', models.TimeField(default='21:00')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'shift_start'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ASSIGN', 'Assign Bus to Route'), ('REMOVE', 'Remove Bus from Route'), ('EXTRA_TRIP', 'Create Extra Trip'), ('BREAKDOWN', 'Mark Bus Breakdown'), ('REASSIGN', 'Reassign Replacement Bus'), ('DELAY', 'Report Delay'), ('STATUS_UPDATE', 'Status Update'), ('GENERATE_SCHEDULE', 'Generate Daily Schedule')], max_length=20)),
                ('vehicle_id', models.UUIDField(blank=True, null=True)),
                ('route_id', models.UUIDField(blank=True, null=True)),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('performed_by_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dispatch.dailyallocation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyallocation',
            index=models.Index(fields=['date', 'status'], name='dispatch_da_date_168dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyallocation',
            index=models.Index(fields=['date', 'route_id'], name='dispatch_da_date_606de5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyallocation',
            index=models.Index(fields=['vehicle_id', 'date'], name='dispatch_da_vehicle_fa23a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyallocation',
            unique_together={('date', 'vehicle_id')},
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['timestamp'], name='dispatch_di_timesta_5b87fd_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['action_type'], name='dispatch_di_action__0cce98_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchlog',
            index=models.Index(fields=['vehicle_id', 'timestamp'], name='dispatch_di_vehicle_7e8d72_idx'),
        ),
    ]
