# Generated by Django 4.2.16 on 2026-10-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyallocation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispatchlog',
            name='action_type',
            field=models.CharField(choices=[('ASSIGN', 'Assign Bus to Route'), ('REMOVE', 'Remove Bus from Route'), ('EXTRA_TRIP', 'Create Extra Trip'), ('BREAKDOWN', 'Mark Bus Breakdown'), ('REASSIGN', 'Reassign Replacement Bus'), ('DELAY', 'Report Delay'), ('STATUS_UPDATE', 'Status Update'), ('GENERATE_SCHEDULE', 'Generate Daily Schedule'), ('AUTO_COMPLETE', 'Shift Auto-Completed'), ('AUTO_RECUR', 'Recurring Allocation Auto-Created')], max_length=20),
        ),
    ]
