# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_ne', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TRANSPORT_AUTHORITY_OFFICER', 'Transport Authority Officer'), ('REVENUE_AUDITOR', 'Revenue Auditor'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('PLATFORM_SUPPORT', 'Platform Support'), ('COMPANY_ADMIN', 'Company Admin'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('DISPATCHER', 'Dispatcher'), ('FLEET_MANAGER', 'Fleet Manager'), ('MAINTENANCE_MANAGER', 'Maintenance Manager'), ('FINANCE_OFFICER', 'Finance Officer'), ('HR_OFFICER', 'HR Officer'), ('STATION_MANAGER', 'Station Manager'), ('DRIVER', 'Driver'), ('CONDUCTOR', 'Conductor'), ('INSPECTOR', 'Inspector'), ('PASSENGER', 'Passenger'), ('STUDENT', 'Student'), ('TOURIST', 'Tourist')], default='PASSENGER', max_length=50)),
                ('language_preference', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('tenant_schema', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='users_user_email_6f2530_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx'), models.Index(fields=['tenant_schema'], name='users_user_tenant__a5a0fd_idx')],
            },
        ),
    ]
