# Generated by Django 4.2.16 on 2026-08-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_partner_federated_login'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_partner_4b5ae5_idx',
            old_name='users_user_partner_ce49a4_idx',
        ),
    ]
