# Generated by Django 4.2.16 on 2026-08-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_users_user_partner_ce49a4_idx_users_user_partner_4b5ae5_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        # AlterField's default='' above is Django/ORM-level only -- it does
        # NOT add an actual Postgres column default (that needs Django 5's
        # db_default, not available on this Django 4.2). Without this, any
        # raw SQL INSERT that omits the "partner" column (e.g.
        # fastapi_services/public_api/tenant_db.py's self-service-account
        # bootstrap) violates the NOT NULL constraint added in migration
        # 0002 -- a real bug, only surfaced once a federated-login user
        # actually triggered self-service account creation against a live DB.
        migrations.RunSQL(
            sql="ALTER TABLE users_user ALTER COLUMN partner SET DEFAULT '';",
            reverse_sql="ALTER TABLE users_user ALTER COLUMN partner DROP DEFAULT;",
        ),
    ]
