# Generated by Django 4.2.16 on 2026-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TRANSPORT_AUTHORITY_OFFICER', 'Transport Authority Officer'), ('REVENUE_AUDITOR', 'Revenue Auditor'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('PLATFORM_SUPPORT', 'Platform Support'), ('COMPANY_ADMIN', 'Company Admin'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('DISPATCHER', 'Dispatcher'), ('FLEET_MANAGER', 'Fleet Manager'), ('MAINTENANCE_MANAGER', 'Maintenance Manager'), ('FINANCE_OFFICER', 'Finance Officer'), ('HR_OFFICER', 'HR Officer'), ('STATION_MANAGER', 'Station Manager'), ('DRIVER', 'Driver'), ('CONDUCTOR', 'Conductor'), ('INSPECTOR', 'Inspector'), ('OWNER', 'Bus Owner'), ('PASSENGER', 'Passenger'), ('STUDENT', 'Student'), ('TOURIST', 'Tourist')], default='PASSENGER', max_length=50),
        ),
    ]
