# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('tax_pan', models.CharField(blank=True, max_length=20)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bus Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_type', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='company_licenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_ne', models.CharField(blank=True, max_length=255)),
                ('citizenship_no', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conductor_photos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=15)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='ConductorAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_ne', models.CharField(blank=True, max_length=255)),
                ('dob', models.DateField()),
                ('citizenship_no', models.CharField(max_length=50)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(max_length=10)),
                ('license_expiry', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='driver_photos/')),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('PART_TIME', 'Part Time')], max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='TicketCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField()),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by_id', models.UUIDField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='staff.conductor')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='staff.driver')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DriverTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='training_certs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='staff.driver')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DriverPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the month')),
                ('trips_completed', models.PositiveIntegerField(default=0)),
                ('on_time_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('complaints_received', models.PositiveSmallIntegerField(default=0)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='staff.driver')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='DriverMedical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examination_date', models.DateField()),
                ('doctor', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('FIT', 'Fit'), ('UNFIT', 'Unfit'), ('CONDITIONAL', 'Conditionally Fit')], max_length=15)),
                ('valid_until', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicals', to='staff.driver')),
            ],
            options={
                'ordering': ['-examination_date'],
            },
        ),
        migrations.CreateModel(
            name='DriverAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ON_LEAVE', 'On Leave')], default='PRESENT', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.driver')),
            ],
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['employee_id'], name='staff_drive_employe_f81f17_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_no'], name='staff_drive_license_961291_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='staff_drive_status_7ee9ed_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_expiry'], name='staff_drive_license_7b6de6_idx'),
        ),
        migrations.AddField(
            model_name='conductorattendance',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.conductor'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['employee_id'], name='staff_condu_employe_44d85d_idx'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['status'], name='staff_condu_status_d05ae3_idx'),
        ),
        migrations.AddField(
            model_name='companylicense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='staff.buscompany'),
        ),
        migrations.AddIndex(
            model_name='ticketcollection',
            index=models.Index(fields=['conductor', 'trip_id'], name='staff_ticke_conduct_96a48e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverperformance',
            unique_together={('driver', 'month')},
        ),
        migrations.AddIndex(
            model_name='driverattendance',
            index=models.Index(fields=['driver', 'date'], name='staff_drive_driver__4a52fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverattendance',
            unique_together={('driver', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='conductorattendance',
            unique_together={('conductor', 'date')},
        ),
        migrations.AddIndex(
            model_name='companylicense',
            index=models.Index(fields=['company', 'expiry_date'], name='staff_compa_company_994f2d_idx'),
        ),
    ]
