# Generated by Django 4.2.16 on 2026-06-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AddField(
            model_name='driver',
            name='bus_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_medical_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issuing_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='previous_employer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='route_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning (5am–12pm)'), ('DAY', 'Day (12pm–6pm)'), ('EVENING', 'Evening (6pm–10pm)'), ('NIGHT', 'Night (10pm–5am)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='employment_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('PART_TIME', 'Part Time')], default='PERMANENT', max_length=15),
        ),
    ]
