# Generated by Django 4.2.16 on 2026-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_conductor_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning (5am–12pm)'), ('DAY', 'Day (12pm–6pm)'), ('EVENING', 'Evening (6pm–10pm)'), ('NIGHT', 'Night (10pm–5am)')], max_length=10),
        ),
    ]
