# Generated by Django 4.2.16 on 2026-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_salary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='citizenship_photo',
            field=models.ImageField(blank=True, null=True, upload_to='conductor_citizenship_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_license_photos/'),
        ),
    ]
