# Generated by Django 4.2.16 on 2026-09-20 04:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_conductor_citizenship_photo_driver_license_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conductor_user_id', models.UUIDField()),
                ('vehicle_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateField()),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('declared_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('system_cash_total', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('closed_by_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
