# Generated by Django 4.2.16 on 2026-09-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_conductorshift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConductorShift',
        ),
    ]
