# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardRecharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharge_method', models.CharField(choices=[('CASH', 'Cash'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('FONEPAY', 'Fonepay'), ('CONNECT_IPS', 'ConnectIPS')], max_length=15)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='COMPLETED', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit'), ('RECHARGE', 'Recharge')], max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_type', models.CharField(choices=[('STUDENT', 'Student'), ('SENIOR', 'Senior Citizen'), ('DISABILITY', 'Disability')], max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DistanceFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('per_km_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_fare', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='FareMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_from', models.CharField(blank=True, max_length=50)),
                ('zone_to', models.CharField(blank=True, max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peak_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('student_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeakFareSurcharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peak_start', models.TimeField()),
                ('peak_end', models.TimeField()),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ne', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('route_type', models.CharField(choices=[('EXCLUSIVE', 'Exclusive'), ('SHARED', 'Shared')], default='EXCLUSIVE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('geojson_path', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route_code'],
            },
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDiversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('alternate_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('estimated_time_from_start', models.PositiveIntegerField(help_text='Minutes from route start')),
            ],
            options={
                'ordering': ['route', 'sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='RouteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveSmallIntegerField()),
                ('change_summary', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('snapshot', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='SmartCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ne', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('has_shelter', models.BooleanField(default=False)),
                ('has_digital_signage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stop_code'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ne', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('validity_hours', models.PositiveSmallIntegerField(default=4)),
                ('is_transferable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneFare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_from', models.CharField(max_length=50)),
                ('zone_to', models.CharField(max_length=50)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_fares', to='platform.farepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='StopAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('boarding_count', models.PositiveIntegerField(default=0)),
                ('alighting_count', models.PositiveIntegerField(default=0)),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='platform.stop')),
            ],
        ),
        migrations.CreateModel(
            name='StopAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amenity_type', models.CharField(choices=[('TOILET', 'Toilet'), ('DRINKING_WATER', 'Drinking Water'), ('SEATING', 'Seating'), ('RAMP', 'Wheelchair Ramp'), ('CCTV', 'CCTV'), ('LIGHTING', 'Lighting')], max_length=30)),
                ('status', models.CharField(choices=[('FUNCTIONAL', 'Functional'), ('BROKEN', 'Broken'), ('UNDER_REPAIR', 'Under Repair')], default='FUNCTIONAL', max_length=20)),
                ('last_maintained', models.DateField(blank=True, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='platform.stop')),
            ],
        ),
    ]
