# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smartcard',
            name='issued_by_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='smartcard',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smart_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeversion',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeversion',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='platform.route'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='platform.route'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='platform.stop'),
        ),
        migrations.AddField(
            model_name='routediversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routediversion',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diversions_end', to='platform.stop'),
        ),
        migrations.AddField(
            model_name='routediversion',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversions', to='platform.route'),
        ),
        migrations.AddField(
            model_name='routediversion',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diversions_start', to='platform.stop'),
        ),
        migrations.AddField(
            model_name='routeassignment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='platform.route'),
        ),
        migrations.AddField(
            model_name='routeassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='route',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_as_end', to='platform.stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_as_start', to='platform.stop'),
        ),
        migrations.AddField(
            model_name='peakfaresurcharge',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_surcharges', to='platform.farepolicy'),
        ),
        migrations.AddField(
            model_name='farepolicy',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='platform.route'),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fares', to='platform.tickettype'),
        ),
        migrations.AddField(
            model_name='farematrix',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distancefare',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_fares', to='platform.farepolicy'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='platform.farepolicy'),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='platform.smartcard'),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='cardrecharge',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharges', to='platform.smartcard'),
        ),
        migrations.AddIndex(
            model_name='stopanalytics',
            index=models.Index(fields=['stop', 'date'], name='platform_st_stop_id_e563de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stopanalytics',
            unique_together={('stop', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='stopamenity',
            unique_together={('stop', 'amenity_type')},
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['stop_code'], name='platform_st_stop_co_db3d89_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['status'], name='platform_st_status_a666b0_idx'),
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['is_deleted'], name='platform_st_is_dele_18117e_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcard',
            index=models.Index(fields=['card_no'], name='platform_sm_card_no_880905_idx'),
        ),
        migrations.AddIndex(
            model_name='smartcard',
            index=models.Index(fields=['passenger', 'status'], name='platform_sm_passeng_d21a27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routeversion',
            unique_together={('route', 'version_no')},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'sequence_no'), ('route', 'stop')},
        ),
        migrations.AddIndex(
            model_name='routediversion',
            index=models.Index(fields=['route', 'start_time'], name='platform_ro_route_i_ca2b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='routeassignment',
            index=models.Index(fields=['route', 'status'], name='platform_ro_route_i_2c651d_idx'),
        ),
        migrations.AddIndex(
            model_name='routeassignment',
            index=models.Index(fields=['tenant', 'status'], name='platform_ro_tenant__289e54_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_code'], name='platform_ro_route_c_8d0408_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['status'], name='platform_ro_status_9b0fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_type'], name='platform_ro_route_t_74369f_idx'),
        ),
        migrations.AddIndex(
            model_name='farematrix',
            index=models.Index(fields=['route', 'ticket_type'], name='platform_fa_route_i_4cb684_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card', 'timestamp'], name='platform_ca_card_id_cf8527_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['transaction_type'], name='platform_ca_transac_66fb09_idx'),
        ),
        migrations.AddIndex(
            model_name='cardrecharge',
            index=models.Index(fields=['card', 'timestamp'], name='platform_ca_card_id_3c5b62_idx'),
        ),
    ]
