# Generated by Django 4.2.16 on 2026-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0003_route_nullable_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
