# Generated by Django 4.2.16 on 2026-09-14 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0008_routestop_status_adminnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('order', models.PositiveSmallIntegerField(help_text='Position along the route path, start to end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_stops', to='platform.route')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
    ]
