# Generated by Django 4.2.16 on 2026-09-16 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0009_suggestedstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('PER_VEHICLE', 'Per Vehicle'), ('GROUP_LEVEL', 'Group Level')], default='PER_VEHICLE', max_length=15)),
                ('min_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('require_ac', models.BooleanField(default=False)),
                ('allowed_categories', models.JSONField(blank=True, default=list, help_text='List of VehicleCategory codes')),
                ('permit_class', models.CharField(blank=True, max_length=50)),
                ('min_total_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('min_ac_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category_bounds', models.JSONField(blank=True, default=dict, help_text='e.g. {"MICRO-18": {"max": 1}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='platform.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('HOLIDAY', 'Holiday')], max_length=10)),
                ('slot_count', models.PositiveSmallIntegerField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_profiles', to='platform.route')),
            ],
            options={
                'ordering': ['route', 'day_type', '-effective_from'],
                'unique_together': {('route', 'day_type', 'effective_from')},
            },
        ),
    ]
