# Generated by Django 4.2.16 on 2026-09-20 04:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0010_routerequirement_routedemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='farematrix',
            name='child_fare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
