# Generated by Django 4.2.16 on 2026-09-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_pan_vat_number'),
        ('platform', '0011_farematrix_child_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('tenant', 'code')},
        ),
    ]
