# Generated by Django 4.2.16 on 2026-10-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0012_tickettype_tenant_alter_tickettype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farematrix',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='platform.tickettype'),
        ),
    ]
