# Generated by Django 4.2.16 on 2026-06-21 06:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('AMC', 'Fixed Monthly AMC'), ('PER_TICKET_PERCENTAGE', 'Per Ticket — % of Revenue'), ('PER_TICKET_FIXED', 'Per Ticket — Fixed Amount'), ('PER_TRANSACTION_PERCENTAGE', 'Per Transaction — % of Revenue'), ('PER_TRANSACTION_FIXED', 'Per Transaction — Fixed Amount'), ('PER_BUS', 'Per Active Bus')], max_length=30)),
                ('billing_model', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], max_length=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rule_type'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('tenant_name', models.CharField(max_length=255)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('WAIVED', 'Waived')], default='PENDING', max_length=10)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_prorated', models.BooleanField(default=False)),
                ('proration_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63, unique=True)),
                ('tenant_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=10)),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=7)),
                ('grace_period_end', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.pricingplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('active_buses', models.PositiveSmallIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='billing.tenantsubscription')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('override_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='billing.commissionrule')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_overrides', to='billing.tenantsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('CONNECT_IPS', 'ConnectIPS'), ('FONEPAY', 'FonePay'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('MANUAL', 'Manual (Admin Entry)'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=15)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('unit_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['rule_type'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.tenantsubscription'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='usage_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.usagemetric'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='billing.pricingplan'),
        ),
        migrations.CreateModel(
            name='BillingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('action', models.CharField(choices=[('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('SUBSCRIPTION_SUSPENDED', 'Subscription Suspended'), ('SUBSCRIPTION_ACTIVATED', 'Subscription Activated'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('SUBSCRIPTION_RENEWED', 'Subscription Renewed'), ('INVOICE_GENERATED', 'Invoice Generated'), ('INVOICE_CANCELLED', 'Invoice Cancelled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('PLAN_CHANGED', 'Pricing Plan Changed'), ('GRACE_PERIOD_STARTED', 'Grace Period Started'), ('LATE_FEE_APPLIED', 'Late Fee Applied'), ('USAGE_COLLECTED', 'Usage Metrics Collected')], max_length=25)),
                ('performed_by_id', models.UUIDField(blank=True, null=True)),
                ('performed_by_email', models.CharField(blank=True, max_length=254)),
                ('related_invoice_id', models.UUIDField(blank=True, null=True)),
                ('related_subscription_id', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'created_at'], name='billing_bil_tenant__580ca7_idx'), models.Index(fields=['action'], name='billing_bil_action_cccdef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usagemetric',
            index=models.Index(fields=['tenant_schema', 'period_start', 'period_end'], name='billing_usa_tenant__fef3de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagemetric',
            unique_together={('tenant_schema', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant_schema', 'status'], name='billing_ten_tenant__3614b2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['end_date'], name='billing_ten_end_dat_bbe952_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['status'], name='billing_ten_status_f310f6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncommissionrule',
            index=models.Index(fields=['subscription', 'is_active'], name='billing_sub_subscri_fe2119_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptioncommissionrule',
            unique_together={('subscription', 'commission_rule')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_status'], name='billing_pay_invoice_6134b0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='billing_pay_transac_904624_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant_schema', 'payment_status'], name='billing_inv_tenant__3f4319_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'payment_status'], name='billing_inv_due_dat_6589af_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['billing_period_start', 'billing_period_end'], name='billing_inv_billing_3c8247_idx'),
        ),
    ]
