# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_type', models.CharField(choices=[('PARTS', 'Parts'), ('LABOR', 'Labor'), ('OTHER', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('service_type', models.CharField(choices=[('PERIODIC', 'Periodic Service'), ('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('EMERGENCY', 'Emergency')], max_length=15)),
                ('due_date', models.DateField()),
                ('due_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('mechanic', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_used', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='maintenance.maintenanceschedule')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.workshop')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['vehicle_id', 'status'], name='maintenance_vehicle_8543f9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['due_date'], name='maintenance_due_dat_a2d55c_idx'),
        ),
        migrations.AddField(
            model_name='maintenancecost',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='maintenance.servicerecord'),
        ),
        migrations.AddIndex(
            model_name='servicerecord',
            index=models.Index(fields=['vehicle_id', 'start_date'], name='maintenance_vehicle_a6bc1f_idx'),
        ),
    ]
