# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('capacity_seated', models.PositiveSmallIntegerField()),
                ('capacity_standing', models.PositiveSmallIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_MAINTENANCE', 'In Maintenance'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired'), ('BREAKDOWN', 'Breakdown')], default='ACTIVE', max_length=20)),
                ('assigned_route_id', models.UUIDField(blank=True, null=True)),
                ('current_driver_id', models.UUIDField(blank=True, null=True)),
                ('gps_device_id', models.CharField(blank=True, max_length=50)),
                ('chassis_no', models.CharField(max_length=50, unique=True)),
                ('engine_no', models.CharField(blank=True, max_length=50)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['registration_no'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255)),
                ('policy_no', models.CharField(max_length=100)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleGPS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('provider', models.CharField(max_length=100)),
                ('sim_no', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAULT', 'Fault')], default='ACTIVE', max_length=10)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_device', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('BLUEBOOK', 'Bluebook (Nagarik Praman Patra)'), ('INSURANCE', 'Insurance'), ('POLLUTION', 'Pollution Certificate'), ('ROUTE_PERMIT', 'Route Permit'), ('TAX', 'Tax Receipt')], max_length=15)),
                ('doc_no', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_no'], name='fleet_vehic_registr_47fce3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='fleet_vehic_status_f5cfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_deleted'], name='fleet_vehic_is_dele_302b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinsurance',
            index=models.Index(fields=['vehicle', 'end_date'], name='fleet_vehic_vehicle_84e212_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['vehicle', 'doc_type'], name='fleet_vehic_vehicle_5e8252_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicledocument',
            index=models.Index(fields=['expiry_date'], name='fleet_vehic_expiry__020259_idx'),
        ),
    ]
