# Generated by Django 4.2.16 on 2026-06-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity_cc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('BUS', 'Bus'), ('MICROBUS', 'Microbus'), ('MINIBUS', 'Minibus'), ('TEMPO', 'Tempo'), ('ELECTRIC_BUS', 'Electric Bus')], default='BUS', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_type',
            field=models.CharField(choices=[('BLUEBOOK', 'Bluebook (Nagarik Praman Patra)'), ('INSURANCE', 'Insurance'), ('POLLUTION', 'Pollution Certificate'), ('ROUTE_PERMIT', 'Route Permit'), ('TAX', 'Tax Receipt'), ('FITNESS', 'Fitness / Inspection Certificate')], max_length=15),
        ),
    ]
