# Generated by Django 4.2.16 on 2026-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_add_vehicle_type_color_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bus_number',
            field=models.CharField(blank=True, help_text='Display bus number (e.g. Bus 1, KV-001)', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_conductor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('IN_SERVICE', 'In Service'), ('IN_MAINTENANCE', 'In Maintenance'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired'), ('BREAKDOWN', 'Breakdown')], default='ACTIVE', max_length=20),
        ),
    ]
