# Generated by Django 4.2.16 on 2026-09-16 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_owner_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short handle, e.g. G-03', max_length=20, unique=True)),
                ('kind', models.CharField(choices=[('ROTATING', 'Rotating'), ('FIXED', 'Fixed'), ('RESERVE', 'Reserve')], default='ROTATING', max_length=10)),
                ('composition_mode', models.CharField(choices=[('UNIFORM', 'Uniform'), ('MIXED', 'Mixed')], default='UNIFORM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('capability_min_seats', models.PositiveSmallIntegerField(default=0)),
                ('capability_total_seats', models.PositiveIntegerField(default=0)),
                ('capability_all_ac', models.BooleanField(default=False)),
                ('capability_ac_count', models.PositiveSmallIntegerField(default=0)),
                ('capability_categories', models.JSONField(blank=True, default=dict, help_text='{category_code: member_count}')),
                ('capability_permit_classes', models.JSONField(blank=True, default=list)),
                ('capability_computed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_deleted'], name='fleet_vehic_is_dele_3a7630_idx'), models.Index(fields=['kind'], name='fleet_vehic_kind_47bccf_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Short handle, e.g. DLX-35', max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ne', models.CharField(blank=True, max_length=255)),
                ('seating_capacity', models.PositiveSmallIntegerField()),
                ('body_class', models.CharField(choices=[('MICRO', 'Micro'), ('MINI', 'Mini'), ('STANDARD', 'Standard'), ('DELUXE', 'Deluxe')], default='STANDARD', max_length=10)),
                ('air_conditioned', models.BooleanField(default=False)),
                ('fuel_type', models.CharField(choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('CNG', 'CNG'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='DIESEL', max_length=10)),
                ('permit_class', models.CharField(blank=True, max_length=50)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Open extension: low floor, luggage rack, WiFi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'vehicle categories',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_deleted'], name='fleet_vehic_is_dele_7fe6d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupCompositionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_mixed', models.BooleanField(default=True)),
                ('group_size', models.PositiveSmallIntegerField(default=4)),
                ('max_categories_per_group', models.PositiveSmallIntegerField(default=2)),
                ('capacity_spread_limit', models.PositiveSmallIntegerField(default=15, help_text='Largest allowed seat gap between the biggest and smallest member')),
                ('permit_class_match', models.BooleanField(default=True)),
                ('required_composition', models.JSONField(blank=True, help_text="Optional template, e.g. {'DLX-35': 2, 'STD-40': 2}", null=True)),
                ('spares_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composition_rule', to='fleet.vehiclegroup')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.vehiclecategory'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fleet.vehiclegroup')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_memberships', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['group', 'valid_to'], name='fleet_group_group_i_30f78e_idx'), models.Index(fields=['vehicle', 'valid_to'], name='fleet_group_vehicle_548d2c_idx')],
            },
        ),
    ]
