# Generated by Django 4.2.16 on 2026-09-16 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehiclegroup_vehiclecategory_groupcompositionrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDriverAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_user_id', models.UUIDField()),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='fleet.vehiclegroup')),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['group', 'valid_to'], name='fleet_group_group_i_c37238_idx'), models.Index(fields=['driver_user_id', 'valid_to'], name='fleet_group_driver__ca02bd_idx')],
            },
        ),
    ]
