# Generated by Django 4.2.16 on 2026-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_groupdriverassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegroup',
            name='ring_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
