# Generated by Django 4.2.16 on 2026-09-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehiclegroup_ring_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegroup',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclegroup',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
