# Generated by Django 4.2.16 on 2026-09-17 03:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehiclegroup_home_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConductorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conductor_user_id', models.UUIDField()),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_assignments', to='fleet.vehiclegroup')),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['group', 'valid_to'], name='fleet_group_group_i_c41894_idx'), models.Index(fields=['conductor_user_id', 'valid_to'], name='fleet_group_conduct_b7ee0a_idx')],
            },
        ),
    ]
