# Generated by Django 4.2.16 on 2026-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_groupconductorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('IN_SERVICE', 'In Service'), ('IN_MAINTENANCE', 'In Maintenance'), ('INACTIVE', 'Inactive'), ('RETIRED', 'Retired'), ('BREAKDOWN', 'Breakdown'), ('RESERVE', 'Reserve')], default='ACTIVE', max_length=20),
        ),
    ]
