# Generated by Django 4.2.16 on 2026-09-25 15:32

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_owner_vehicle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='temp_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
