# Generated by Django 4.2.16 on 2026-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_owner_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
