# Generated by Django 4.2.16 on 2026-09-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_owner_bank_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_photos/'),
        ),
    ]
