# Generated by Django 4.2.16 on 2026-09-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_owner_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='citizenship_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_citizenship_photos/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='citizenship_photo_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
