# Generated by Django 4.2.16 on 2026-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_owner_citizenship_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='standing_conductor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='standing_driver_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
