# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_no', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('BREAKDOWN', 'Breakdown'), ('CRIME', 'Crime'), ('MEDICAL_EMERGENCY', 'Medical Emergency'), ('OTHER', 'Other')], max_length=20)),
                ('vehicle_id', models.UUIDField(blank=True, null=True)),
                ('driver_id', models.UUIDField(blank=True, null=True)),
                ('route_id', models.UUIDField(blank=True, null=True)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('reported_by_id', models.UUIDField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_no', models.CharField(max_length=50)),
                ('insurer', models.CharField(max_length=255)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('FILED', 'Filed'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLED', 'Settled')], default='FILED', max_length=15)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='incidents.incident')),
            ],
            options={
                'ordering': ['-filed_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='incident_media/')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='incidents.incident')),
            ],
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='incidents_i_severit_10e3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['vehicle_id'], name='incidents_i_vehicle_e7d67e_idx'),
        ),
    ]
