# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('DRIVER', 'Driver'), ('VEHICLE', 'Vehicle'), ('COMPANY', 'Company')], max_length=10)),
                ('entity_id', models.UUIDField()),
                ('doc_category', models.CharField(choices=[('LICENSE', 'License'), ('CITIZENSHIP', 'Citizenship'), ('TRAINING', 'Training Certificate'), ('MEDICAL', 'Medical Clearance'), ('BLUEBOOK', 'Bluebook'), ('INSURANCE', 'Insurance'), ('ROUTE_PERMIT', 'Route Permit'), ('POLLUTION', 'Pollution Certificate'), ('TAX', 'Tax Receipt'), ('REGISTRATION', 'Registration'), ('PAN', 'PAN Certificate'), ('CONTRACT', 'Government Contract'), ('OTHER', 'Other')], max_length=15)),
                ('doc_type', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='documents/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('doc_no', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_by_id', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_by_id', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days_to_expiry', models.IntegerField()),
                ('alert_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='documents.document')),
            ],
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['entity_type', 'entity_id'], name='documents_d_entity__bec8fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['verified'], name='documents_d_verifie_132bda_idx'),
        ),
    ]
