"""
Tests confirming qr_code is returned by the ticket read endpoints
(GET /tickets/{id}/ and GET /tickets/my/), not just the direct
POST /tickets/ issuance response.

Before this fix, qr_code was generated by Django at issuance (and returned
verbatim on that one POST /tickets/ response, since it's a straight
passthrough of Django's own JSON) but silently dropped by tenant_db's
cross-schema ticket queries and _serialize_ticket()'s allowlist — so a
passenger's app polling "my tickets" later would get a ticket with no QR
image in it at all.

Mocks tenant_db.find_ticket_by_id/find_tickets_for_passenger — no live
Postgres needed (qr_code is a plain passthrough column, no new query logic).
"""
from unittest.mock import AsyncMock, patch

import pytest
from fastapi.testclient import TestClient
from jose import jwt as jose_jwt

from backend.fastapi_services.config import settings as fastapi_settings
from backend.fastapi_services.main import app
from backend.fastapi_services.public_api import router as public_api_router

JWT_SECRET = fastapi_settings.JWT_SECRET_KEY
JWT_ALG = fastapi_settings.JWT_ALGORITHM

TICKET_ID = "11111111-1111-1111-1111-111111111111"
QR_CODE_B64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="

TICKET_WITH_QR = {
    "id": TICKET_ID,
    "ticket_uid": "TKT-AAA111",
    "tenant_schema": "tenant_a",
    "ticket_type_id": None,
    "trip_id": None,
    "passenger_id": "22222222-2222-2222-2222-222222222222",
    "passenger_name": "Test Passenger",
    "conductor_id": "33333333-3333-3333-3333-333333333333",
    "issued_at": "2026-07-26T10:00:00Z",
    "issued_by": "CONDUCTOR",
    "valid_until": "2026-07-26T23:59:59Z",
    "fare_paid": "30.00",
    "payment_method": "CASH",
    "qr_code": QR_CODE_B64,
    "status": "VALID",
    "from_stop_id": None,
    "to_stop_id": None,
}


def _token(role, user_id, tenant_schema=""):
    return jose_jwt.encode(
        {"user_id": user_id, "role": role, "tenant_schema": tenant_schema}, JWT_SECRET, algorithm=JWT_ALG
    )


@pytest.fixture
def client():
    return TestClient(app)


def test_get_ticket_includes_qr_code(client):
    with patch.object(
        public_api_router.tenant_db, "find_ticket_by_id", new=AsyncMock(return_value=("tenant_a", dict(TICKET_WITH_QR)))
    ), patch.object(public_api_router.tenant_db, "enrich_stop_names", new=AsyncMock()), patch.object(
        public_api_router.tenant_db, "enrich_payment_references", new=AsyncMock()
    ), patch.object(public_api_router.tenant_db, "enrich_passenger_details", new=AsyncMock()):
        resp = client.get(
            f"/public-api/v1/tickets/{TICKET_ID}/",
            headers={"Authorization": f"Bearer {_token('PASSENGER', TICKET_WITH_QR['passenger_id'])}"},
        )

    assert resp.status_code == 200, resp.text
    assert resp.json()["data"]["qr_code"] == QR_CODE_B64


def test_my_tickets_includes_qr_code(client):
    with patch.object(
        public_api_router.tenant_db,
        "find_tickets_for_passenger",
        new=AsyncMock(return_value=[dict(TICKET_WITH_QR)]),
    ), patch.object(public_api_router.tenant_db, "enrich_stop_names", new=AsyncMock()), patch.object(
        public_api_router.tenant_db, "enrich_payment_references", new=AsyncMock()
    ), patch.object(public_api_router.tenant_db, "enrich_passenger_details", new=AsyncMock()):
        resp = client.get(
            "/public-api/v1/tickets/my/",
            headers={"Authorization": f"Bearer {_token('PASSENGER', TICKET_WITH_QR['passenger_id'])}"},
        )

    assert resp.status_code == 200, resp.text
    assert resp.json()["data"][0]["qr_code"] == QR_CODE_B64


def test_ticket_without_stored_qr_code_returns_null(client):
    """A ticket row with no qr_code key at all (e.g. legacy data) shouldn't crash —
    should come back as null, not KeyError."""
    ticket_no_qr = dict(TICKET_WITH_QR)
    del ticket_no_qr["qr_code"]

    with patch.object(
        public_api_router.tenant_db, "find_ticket_by_id", new=AsyncMock(return_value=("tenant_a", ticket_no_qr))
    ), patch.object(public_api_router.tenant_db, "enrich_stop_names", new=AsyncMock()), patch.object(
        public_api_router.tenant_db, "enrich_payment_references", new=AsyncMock()
    ), patch.object(public_api_router.tenant_db, "enrich_passenger_details", new=AsyncMock()):
        resp = client.get(
            f"/public-api/v1/tickets/{TICKET_ID}/",
            headers={"Authorization": f"Bearer {_token('PASSENGER', TICKET_WITH_QR['passenger_id'])}"},
        )

    assert resp.status_code == 200, resp.text
    assert resp.json()["data"]["qr_code"] is None
