# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tenant_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['tenant', 'status'], name='tenants_ten_tenant__679851_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['end_date'], name='tenants_ten_end_dat_94a3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['tenant', 'doc_type'], name='tenants_ten_tenant__4eba19_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantdocument',
            index=models.Index(fields=['verified'], name='tenants_ten_verifie_deef34_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status'], name='tenants_ten_status_e7eaee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['schema_name'], name='tenants_ten_schema__df93bb_idx'),
        ),
    ]
