# Generated by Django 4.2.16 on 2026-09-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_pan_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='pan_vat_number',
            field=models.CharField(max_length=50),
        ),
    ]
