# Generated by Django 4.2.16 on 2026-09-16 07:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0006_groupdriverassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('route_id', models.UUIDField()),
                ('slot_index', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('OVERRIDE', 'Override'), ('RESERVE_FILL', 'Reserve Fill')], default='MANUAL', max_length=15)),
                ('locked', models.BooleanField(default=False, help_text='Protects this cell from reassignment via the grid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duties', to='fleet.vehiclegroup')),
            ],
            options={
                'ordering': ['service_date', 'route_id', 'slot_index'],
            },
        ),
        migrations.CreateModel(
            name='VehicleSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='roster.duty')),
                ('in_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_in', to='fleet.vehicle')),
                ('out_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_out', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=10)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_deleted'], name='roster_rost_is_dele_bfc662_idx'), models.Index(fields=['status'], name='roster_rost_status_2b2651_idx')],
            },
        ),
        migrations.CreateModel(
            name='DutyOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='roster.duty')),
                ('new_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.vehiclegroup')),
                ('previous_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.vehiclegroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='duty',
            name='roster_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='roster.rosterperiod'),
        ),
        migrations.AddIndex(
            model_name='duty',
            index=models.Index(fields=['roster_period', 'service_date'], name='roster_duty_roster__aa6929_idx'),
        ),
        migrations.AddIndex(
            model_name='duty',
            index=models.Index(fields=['group', 'service_date'], name='roster_duty_group_i_ba8345_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='duty',
            unique_together={('roster_period', 'service_date', 'route_id', 'slot_index')},
        ),
    ]
