# Generated by Django 4.2.16 on 2026-09-16 13:11

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ring_step', models.PositiveSmallIntegerField(default=1)),
                ('week_pattern', models.CharField(choices=[('KEEP_ROTATING', 'Keep rotating'), ('REPEAT_WEEK', 'Repeat the week'), ('ROTATING_REPEAT', 'Rotating repeat')], default='KEEP_ROTATING', max_length=20)),
                ('week_step', models.PositiveSmallIntegerField(default=1, help_text='Extra shift applied once per week -- ROTATING_REPEAT only')),
                ('epoch_date', models.DateField(default=datetime.date.today, help_text='Fixed reference date all shift arithmetic counts from')),
                ('same_weekday_lookback_weeks', models.PositiveSmallIntegerField(default=1, help_text='no_same_route_same_weekday, HARD')),
                ('route_cooldown_days', models.PositiveSmallIntegerField(default=3, help_text='route_cooldown_days, SOFT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='duty',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GENERATED', 'Generated'), ('OVERRIDE', 'Override'), ('RESERVE_FILL', 'Reserve Fill')], default='MANUAL', max_length=15),
        ),
    ]
