# Generated by Django 4.2.16 on 2026-09-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rotationpolicy_alter_duty_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='cost_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='P2: the weighted cost components that produced this assignment (GENERATED duties only), for the explain endpoint'),
        ),
        migrations.AddField(
            model_name='rotationpolicy',
            name='consecutive_weight',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rotationpolicy',
            name='fair_share_weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rotationpolicy',
            name='max_consecutive_days_same_route',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='rotationpolicy',
            name='rotation_preference_weight',
            field=models.PositiveSmallIntegerField(default=3, help_text="Cost of deviating from the ring's predicted slot"),
        ),
        migrations.AddField(
            model_name='rotationpolicy',
            name='route_cooldown_weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
