# Generated by Django 4.2.16 on 2026-09-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_duty_cost_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationpolicy',
            name='depot_proximity_weight',
            field=models.PositiveSmallIntegerField(default=0, help_text="Cost per 10km between a group's depot and the route's start stop -- 0 = off"),
        ),
    ]
