# Generated by Django 4.2.16 on 2026-09-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_rotationpolicy_depot_proximity_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationpolicy',
            name='crew_hours_weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cost per hour over crew_max_hours -- 0 = off'),
        ),
        migrations.AddField(
            model_name='rotationpolicy',
            name='crew_max_hours',
            field=models.PositiveSmallIntegerField(default=15, help_text="Max scheduled hours/day for a group's bound crew before crew_hours_weight kicks in"),
        ),
    ]
