# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_no', models.CharField(max_length=20, unique=True)),
                ('passenger_id', models.UUIDField(blank=True, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=255)),
                ('passenger_phone', models.CharField(blank=True, max_length=20)),
                ('complaint_type', models.CharField(choices=[('LATE_BUS', 'Late Bus'), ('DRIVER_BEHAVIOR', 'Driver Behavior'), ('CONDUCTOR_BEHAVIOR', 'Conductor Behavior'), ('TICKET_ISSUE', 'Ticket Issue'), ('CLEANLINESS', 'Cleanliness'), ('OVERCROWDING', 'Overcrowding'), ('SAFETY', 'Safety'), ('OTHER', 'Other')], max_length=25)),
                ('description', models.TextField()),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20)),
                ('route_id', models.UUIDField(blank=True, null=True)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolved_by_id', models.UUIDField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField()),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_to_id', models.UUIDField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tenant_id'], name='complaints__tenant__a942d4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_type'], name='complaints__complai_462a7a_idx'),
        ),
    ]
