# Generated by Django 4.2.16 on 2026-09-26 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_by_id', models.UUIDField()),
                ('category', models.CharField(choices=[('BUG', "Bug / Something's broken"), ('QUESTION', 'Question'), ('FEATURE_REQUEST', 'Feature Request'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reported_by_id', '-created_at'], name='complaints__reporte_3a8844_idx')],
            },
        ),
    ]
