# Generated by Django 4.2.16 on 2026-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScheduleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_id', models.UUIDField(unique=True)),
                ('min_headway_minutes', models.PositiveSmallIntegerField(default=15)),
                ('peak_buses', models.PositiveSmallIntegerField(default=5)),
                ('off_peak_buses', models.PositiveSmallIntegerField(default=3)),
                ('peak_start', models.TimeField(default='07:00')),
                ('peak_end', models.TimeField(default='09:00')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.UUIDField()),
                ('date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_id', models.UUIDField()),
                ('day_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('HOLIDAY', 'Holiday')], max_length=10)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['route_id', 'day_type'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('frequency_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.timetable')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_code', models.CharField(max_length=30, unique=True)),
                ('vehicle_id', models.UUIDField()),
                ('driver_id', models.UUIDField()),
                ('conductor_id', models.UUIDField(blank=True, null=True)),
                ('route_id', models.UUIDField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DELAYED', 'Delayed')], default='SCHEDULED', max_length=15)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timetable_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='scheduling.timetableslot')),
            ],
            options={
                'ordering': ['-date', 'trip_code'],
            },
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['route_id', 'day_type'], name='scheduling__route_i_fad888_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['effective_date'], name='scheduling__effecti_4fc7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='drivershift',
            index=models.Index(fields=['driver_id', 'date'], name='scheduling__driver__084153_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drivershift',
            unique_together={('driver_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date', 'status'], name='scheduling__date_1500db_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle_id', 'date'], name='scheduling__vehicle_65c8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver_id', 'date'], name='scheduling__driver__9a4618_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route_id', 'date'], name='scheduling__route_i_6ed65d_idx'),
        ),
    ]
