# Generated by Django 4.2.16 on 2026-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='scheduled_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='scheduled_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
